version: "3"

services: 
    monolithic:
        build: ./monolithic
    users:
        build: ./microservices/user-service
    books:
        build: ./microservices/book-service
    cars:
        build: ./microservices/car-service
    nginx:
        image: nginx:latest
        ports: 
            - "8080:8080"
        volumes: 
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on: 
            - monolithic
            - users
            - books
            - cars